---
title: "README"
author: "Leonce Nshuti"
output: html_document
---

```{r setup, include=FALSE}
repo_ <- "environmental-impact-driving"
source(paste0(repo_, "/R/manifest.R"))
#source("R/data_aggregation_task.R")

sitc_xwalk <-
  read_csv(paste0(repo_,"/inputs/sitc_product_code.csv")) %>%
  janitor::clean_names() %>%
  mutate(product_code = str_pad(product_code, width = 5, side = c("left"), pad = "0"))

rwa_sum <-
  read_rds(paste0(repo_, "/inputs/rwanda_trade_df_1999_2019.rds")) %>%
  mutate(sitc_product_code = str_pad(sitc_product_code,
                                     width = 5, side = c("left"), pad = "0")) %>%
  left_join(sitc_xwalk, by = c("sitc_product_code"= "product_code")) %>%
  rename(product_name = product_description) %>%
  mutate(import_value = as.numeric(import_value),
         product_name = str_to_lower(product_name),
         export_value = as.numeric(export_value)) %>%
  mutate(year =  as.Date(as.character(year), format = "%Y")) %>%
  mutate(year = lubridate::year(year)) #%>%
  #sample_n(10000)

rwa_summary <-
  rwa_sum %>% 
  group_by(product_name, year) %>%
  summarise(imports = sum(import_value, na.rm = TRUE), exports = sum(export_value, na.rm = TRUE)) %>%
  ungroup() %>%
  rename(name = product_name) %>%
  mutate(name = ifelse(grepl("gold|mineraks|aluminium|iron/st|steel|minerals|tin ores|base metal", name), " metals", name)) %>%
  mutate(name = ifelse(grepl("cement|refract bricks", name), "cement & construct mat", name)) %>%
  mutate(name = ifelse(grepl("kraft uncoat|printed matter|book|typewrirers|paper cartons", name), "books & paper", name)) %>%
  mutate(name = ifelse(grepl("clothing ", name), "clothing",name)) %>%
  mutate(name = ifelse(grepl("generator|dc motor|electric motors", name), "generator",name)) %>%
  mutate(name = ifelse(grepl("aircraft|aircrft|airplanes|helicopters", name), "aircrafts", name)) %>%
  mutate(name = ifelse(grepl("special tra|un special code", name), "special transactions", name)) %>%
  mutate(name = ifelse(grepl("communication|radio|telecom|telephone|computers", name), "telecom", name)) %>%
  mutate(name = ifelse(grepl("petroleum|petrol|crude oil|liquid propane", name), "petroleum", name)) %>%
  mutate(name = ifelse(grepl("lifting|constr/mining|pulley", name), "construction", name)) %>%
  mutate(name = ifelse(grepl("medicaments|glycosides|x-ray|pharmaceutical|pharmaceut", name), "healthcare goods", name)) %>%
  mutate(name = ifelse(grepl("furniture", name), "furniture",name)) %>%
  mutate(name = ifelse(grepl("musical", name), "musical instruments",name)) %>%
  mutate(name = ifelse(grepl("garments", name), "garments",name)) %>%
  mutate(name = ifelse(grepl("office equip", name), "office equipment",name)) %>%
  mutate(name = ifelse(grepl("soap in form of bars", name), "bar soap",name)) %>%
  mutate(name = ifelse(grepl("scientific instrumnt", name), "scientific instrument",name)) %>%
  mutate(name = ifelse(grepl("machine parts|gas turb eng", name), "machine parts",name)) %>%
  mutate(name = ifelse(grepl("indus wash", name), "industrial wash equip",name)) %>%
  mutate(name = ifelse(grepl("acyclic monohyd alcohols", name), "acyclic monohyd alcohols",name)) %>%
  mutate(name = ifelse(grepl("electro-thermic equipmnt", name), "electro-thermic equipment",name)) %>%
  mutate(name = ifelse(grepl("textile|suits", name), "textiles",name)) %>%
  mutate(name = ifelse(grepl("cigarettes", name), "cigarettes",name)) %>%
  mutate(name = ifelse(grepl("plastic", name), "plastic",name)) %>%
  mutate(name = ifelse(grepl("batteries", name), "batteries",name)) %>%
  mutate(name = ifelse(grepl("leather", name), "leather",name)) %>%
  mutate(name = ifelse(grepl("fertilizers", name), "fertilizers",name)) %>%
  mutate(name = ifelse(grepl("vehicles|passenger|tyres|tires|motorcycles|buses|semi-trailer", name), "vehicles & parts", name)) %>%
  mutate(name = ifelse(grepl("beans|legumes|cane|wheat|corn|maize|sugar|soy|meal|cereal|hydrogenated|beet|chocolate|food|strawberries|fish|ruit fresh|beef|groundnuts|nutmeg|milk|salt|vegetables|rice|beer|fixed veg oils|whey|mutton|spices|veg prod ne|malt|veg oil hydrogen|bread|pork|potatoes|coffee|vanilla|fixed veg oil|cinnamon",
                             name), "food products", name)) %>%
  mutate(name = str_trim(name)) %>%
  mutate(len_name = str_length(name)) %>%
  group_by(year) %>%  
  arrange(year, desc(imports)) %>%  
  filter(!is.na(name)) %>%
  # assign ranking
  mutate(rank = 1:n()) %>%  
  ungroup() 

write_rds(x = rwa_summary, file = "rwandatrade/processed/rwa_summary.rds")
#write_rds(x = rwa_summary, file = "rwandatrade/processed/rwa_summary.csv")

rwa_sum_features <- 
  rwa_summary %>% 
  filter(name %in% c("metals", "food products", "fertilizers", "books & paper", "aircrafts", "leather", "healthcare goods",
                     "plastic", "construction", "telecom", "vehicles & parts", "cement", "special transactions", "petroleum",
                     "clothing", "cotton waste", "cement & construct mat", "generator", "cigarettes", "office equipment",
                     "bar soap", "scientific instrument", "textiles", "batteries", "industrial wash equip", 
                     "machine parts", "garments", "childrens toys")) 


tmp <- 
  rwa_summary %>% 
   filter(!(name %in% c("metals", "food products", "fertilizers", "books & paper", "aircrafts", "leather", "healthcare goods",
                     "plastic", "construction", "telecom", "vehicles & parts", "cement", "special transactions", "petroleum",
                     "clothing", "cotton waste", "generator", "cement & construct mat", "cigarettes", "office equipment", 
                     "bar soap", "scientific instrument", "textiles", "batteries", "industrial wash equip", 
                     "machine parts", "garments", "childrens toys"))) %>%
  arrange(rank)
  
write_rds(x = rwa_sum_features, file = "rwandatrade/processed/rwa_sum_features.rds")
# write_csv(x = rwa_sum_features, file = "rwandatrade/processed/rwa_sum_features.csv")
```

```{r}
rwa_sum_rank_plt <- 
  rwa_sum_features %>%
  #filter(year > 2010 & rank < 6) %>%
  ggplot() +  
  aes(xmin = 0,  xmax = log(imports)) +  
  aes(ymin = rank - 0.5, ymax = rank + 0.5, y = rank) +  
  facet_wrap(~ year) +  
  geom_rect(alpha = .7) +  
  aes(fill = name) +  
  #scale_fill_viridis_d(option = "magma", direction = -1) +
  labs(x = 'Imports (millions)', fill = "Product category", y ="") +
  #scale_x_continuous(limits = c(0, 500), breaks = c(0,250,500)) +
  my_theme + 
  theme_bw() +
  theme_tufte_revised() 

ggsave(rwa_sum_rank_plt,width = 10, height = 6,
       filename = "rwandatrade/output/rwanda_imports.png")
```


```{r}
library(idbr)
library(sf)
library(ggiraph)
library(tidyverse)

fertility_data <- get_idb(
  country = "RW",
  year = 2021,
  variables = "tfr",
  geometry = TRUE,
)

fertility_map <-
  ggplot(fertility_data, aes(fill = tfr)) + 
  theme_bw() + 
  geom_sf() + 
  # geom_sf_interactive(aes(tooltip = tooltip, data_id = code), size = 0.1) + 
  coord_sf(crs = 'ESRI:54030') + 
  scale_fill_viridis_c() + 
  labs(fill = "") +
   guides(fill="none")

girafe(ggobj = fertility_map) %>%
  girafe_options(opts_zoom(max = 10))

ggsave(fertility_map,width = 10, height = 6,
       filename = paste0(repo_, "/plots/rwanda_geography.png")
       )
```
