#' Estimate the Market Size for Electic and Plug-In Hybrid Vehicles In Africa
#' The goal of this repository is to use open data repositories to answer the following questions: 
#' 1. What is the estimated market size of electric and hybrid vehicles in Africa? 
#' 2. What is the cost effectiveness of investing in electric vehicles as a public good to clean-up
#     the air of all major African cities?
# 3. What are environmental externalities generated by the extraction of natural resources such as 
#    cobary and Lithium to supply the appetite for batteries for electric vehicles?


import pandas as pd 
from prophet import prophet


###### Case Study: Rwanda

#' Let us start with Rwanda as an example to understand trends in vehicle ownership. According to a report by Bajpai and Bower(2020) from the International Growth Center, there were approximately 221,000 registered vehicles in Rwanda. The same study also states that the growth in vehicle ownership stood at 12% year-over-year. An older(2018) summary report by the Rwanda Bureau of Statistics reported the following trend in vehicle ownership: 

|Year    | N Registred Vehicles 
|---     |--------------------|
|2011    |105545              |
|2012    |125159              |
|2013    |136824              |
|2014    |149012              |
|2015    |166893              |
|2016    |183703              |
-------------------------------
-------------------------------
#' **Source:** *https://theatlas.com/charts/HkTy5aw5G*


#' Pass the above data points to a Python dataframe
rwa_df = [[2011, 105545], [2012, 125159], [2013, 136824],
          [2014, 149012], [2015, 166893], [2016, 183703]]

naive_mod = Prophet()
naive_mod.fit(rwa_df)

# Naive prediction of 2025 vehicle ownership
pr_ownership_25 = naive_mod.make_future_dataframe(periods = 9)


#' References: 

#' **Jitendra Bajpai and Jonathan Bower (2020)** A road map for e-mobility transition in Rwanda (Policy brief 200018).
#'  International Growth Centre. from
#'  https://www.theigc.org/wp-content/uploads/2020/05/Bajpai-and-Bower-2020-policy-brief.pdf 
