#' Estimate the Market Size for Electic and Plug-In Hybrid Vehicles In Africa
#' The goal of this repository is to use open data repositories to answer the following questions: 
#' 1. What is the estimated market size of electric and hybrid vehicles in Africa? 
#' 2. What is the cost effectiveness of investing in electric vehicles as a public good to clean-up
#     the air of all major African cities?
# 3. What are environmental externalities generated by the extraction of natural resources such as 
#    cobary and Lithium to supply the appetite for batteries for electric vehicles?
