#' Estimate the Market Size for Electic and Plug-In Hybrid Vehicles In Africa
#' The goal of this repository is to use open data repositories to answer the following questions: 
#' 1. What is the estimated market size of electric and hybrid vehicles in Africa? 
#' 2. What is the cost effectiveness of investing in electric vehicles as a public good to clean-up
#     the air of all major African cities?
# 3. What are environmental externalities generated by the extraction of natural resources such as 
#    cobary and Lithium to supply the appetite for batteries for electric vehicles?

library(CausalImpact)
library(tidyverse)

rw_auto_ownership <- 
  data.frame(year = 2011:2016, 
             n_registered = c(105545, 125159,  136824, 149012, 166893, 183703)) %>% 
  # Calculate growth rate
  mutate(prev_year = lag(n_registered, 1), change = n_registered - prev_year) %>% 
  mutate(pct_growth = round((change/prev_year)*100, 2))


auto_ownership_plt <- 
  ggplot(rw_auto_ownership, aes(x = year, y = n_registered)) + 
  geom_point() + 
  geom_text(aes(x=year,y= n_registered + 3000, label = pct_growth ), cex = 2) +
  ggthemes::theme_fivethirtyeight() + 
  ggtitle("Vehicle Ownership in Rwanda: Annual % Growth")


ggsave(auto_ownership_plt,
       filename = file.path(here::here(), "GreenAutoImpact.github.io/plots/Rwandaauto_ownership_plt.png")
)