#' Estimate the Market Size for Electic and Plug-In Hybrid Vehicles In Africa
#' The goal of this repository is to use open data repositories to answer the following questions: 
#' 1. What is the estimated market size of electric and hybrid vehicles in Africa? 
#' 2. What is the cost effectiveness of investing in electric vehicles as a public good to clean-up
#     the air of all major African cities?
# 3. What are environmental externalities generated by the extraction of natural resources such as 
#    cobary and Lithium to supply the appetite for batteries for electric vehicles?

library(forecast)
library(tidyverse)
library(lubridate)
library(TSstudio)


rw_auto_ownership <- 
  data.frame(year = 2011:2016, 
             n_registered = c(105545, 125159,  136824, 149012, 166893, 183703)) %>% 
  # Calculate growth rate
  mutate(prev_year = lag(n_registered, 1), change = n_registered - prev_year) %>% 
  mutate(pct_growth = round((change/prev_year)*100, 1)) %>% 
  mutate(pct_growth_str = ifelse(!is.na(pct_growth), paste0(pct_growth, " %"), pct_growth))

auto_ownership_plt <- 
  ggplot(rw_auto_ownership, aes(x = year, y = n_registered)) + 
  geom_point() + 
  geom_text(aes(x=year-0.3,y= n_registered + 3000, label = pct_growth_str), cex = 4) +
  geom_smooth(method = "lm", se = FALSE, aes(color = "brown")) +
  ggtitle("Vehicle Ownership in Rwanda: Annual % Growth") + 
  xlab("Year") +
  ylab("Registered vehicles") + 
  scale_color_manual(values = c("#00AFBB")) +
  theme(axis.text = element_text(size = 10), legend.position = "None")

ggsave(auto_ownership_plt,
       filename = file.path(here::here(), 
                            "GreenAutoImpact.github.io/plots/Rwandaauto_ownership_plt.png"), 
       width = 6, height = 4
)


#' Create a simple time series model to predict future car ownership

ts_df <-
  rw_auto_ownership %>% 
  select(n_registered, year) %>% 
  mutate(year = as.Date(zoo::as.yearmon(year))) %>% 
  rename(y = n_registered, ds = year) 


skirtsseriesforecasts2 <- forecast.HoltWinters(skirtsseriesforecasts, h=3)
plot.forecast(skirtsseriesforecasts2)

ts_df %>% 
  ggplot(., aes(x = ds, y = y)) + 
  geom_point() + 
  ggtitle("Growth Forecast 2025") + 
  xlab("Year") +
  ylab("Registered vehicles") + 
  ggthemes::theme_tufte(base_size = 18) + 
  theme(axis.text = element_text(size = 13), 
        legend.position = "None") + 
  scale_x_date(limit=c(as.Date("2010-01-01"),as.Date("2016-01-01")))
  

lm_mod <- train(Class ~ ., data = ts_df, method = "lm")

